name: distributions release

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-release:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [20.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Install rpm
        run: sudo apt-get install -y rpm
        if: matrix.os == 'ubuntu-latest'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: npm ci
      - run: npm run build
      - name: Build app
        run: ./scripts/make-distributions.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: out/make/*
  release:
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Release App
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            LICENSE
            out/make/*
