name: distributions release

on:
  release:
    branches: [master]
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Install rpm
        run: sudo apt-get install -y rpm
        if: matrix.os == 'ubuntu-latest'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: npm ci
      - run: npm run build
      - name: Build app
        run: ./scripts/make-distributions.sh
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./scripts/release.sh
